
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel1_ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
            };

            Console.WriteLine("Using model to make single prediction -- Comparing actual MEDV with predicted MEDV from sample data...\n\n");





            // Use the model and Prediction Engine to predict on new sample data
            var predictionResult = predEngine.Predict(sampleData);

            Console.WriteLine($"\n\nPredicted MEDV: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
